apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django
        image: django-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: database
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password
---